#+title: Footprinting + Reconnaissance 
#+SETUPFILE:/home/kdb/org-roam/hugo_setup.org
#+HUGO_SECTION: infosec/pentesting
#+hugo_weight: 2


Outline based on the Infrastructure Pentest Series here cite:vijays.

* Scenarios
The context of the penetration test is determined by one of two scenarios, i.e., with the attacker either inside or outside the organization. 
** Outside - External Pentest
The first step when external to the target network is to determine the attack surface. Possible information of interest:
+ Domains/subdomains (e.g., the domain example.com and the subdomain ftp.example.com)
+ IP Addresses / Network Ranges / ASN Number(s)
+ Services / open ports on those IP addresses
+ Employee email addresses
+ Operating systems and software used by the organization
+ Past security breaches
Compromising user creadentials or vulnerable services may lead to internal access
** Inside - Internal Pentest
There are two potential contexts to consider: that of posing as an employee, with access to the internal network; that of an external consultant without internal network access.  We explore the latter case.
* Fingerprinting


During footprinting, you're looking for insight into the target: high-level network architecture (routers, servers), applications and websites, physical security measures (entry control systems).  Also less technical information: critical business functions, key intellectual property, the most sensitive information the company holds, employee information.


Sources for company origin and development:
 + [[www.sec.gov/edgar.shtml][EDGAR Database]]
 + [[www.hoovers.com][Hoovers]]
 + [[www.lexisnexis.com][LexisNexis]]
 + [[www.businesswire.com][Business Wire]]

 For company plans and financials:
 + [[www.secinfo.com][SEC Info]]
 + [[www.experian.com][Experian]]
 + [[www.marketwatch.com][Market Watch]]
 + [[www.twst.com][Wall Street Monitor]]
 + [[www.euromonitor.com][Euromonitor]]

 The company's online reputation is of interest, along with the actual traffic statistics of the company's web traffic ([[www.alexa.com]]). Finally, for company news releases on a timeline of its stock performance, see [[finance.google.com]].
 

